In [2]:
pip install numpy pandas matplotlib scikit-learn openpyxl seaborn


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
print("Best of Luck")

Best of Luck


### NumPy

* Numerical Python - majorly works with array called ndarray
* ndarray --> n-Dimensional array
* statistical library comes with many statistical functions and packages
* NumPy is the fast processed library built with C compiler
* Every NumPy array is already compiled with C , So that it will take less time to execute.
* Why NumPy is developed , when Python already has list data structures?
* NumPy array calculation is done element wise
* Default datatype in NumPy is "FLOAT". It can store string, integer also.
* Tuple can not store single element.


In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr[4]

5

In [8]:
ls2 = [[1,2,3],[4,5,6],[7,8,9]]
ls2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr2 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 # Matrix 3 x 3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2.ndim    # ndim is the number of dimension

2

In [11]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [12]:
ls=[1,2,3,4,5,6,7,8]

In [13]:
ls*2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
[1,2,3]+[4,5,6]    # listwise

[1, 2, 3, 4, 5, 6]

In [15]:
np.array([1,2,3]) + np.array([4,5,6])   # arraywise

array([5, 7, 9])

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr2.shape   # shape shows number of rows and columns

(3, 3)

In [18]:
arr2.size  # size returns number of elements in ndarray

9

In [19]:
arr3 = np.arange(5,67,8)  # only one element in paranthesis means stop element, two element means start, stop element 
# and three element means start,stop,step
arr3

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [20]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.arange(3,10) # why last element '10' is not included?

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
arr4 = np.arange(1,65)

In [23]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [24]:
arr4.ndim  # in 1-D array all the elements are column

1

In [25]:
arr4.shape   # 1 row and 64 columns # tuple can not store single element 

(64,)

In [26]:
arr4.size

64

In [27]:
a = (10)

In [28]:
type(a)

int

In [29]:
b=4,7,2,6

In [30]:
type(b)

tuple

In [31]:
a=(10,)

In [32]:
type(a)

tuple

In [33]:
arr4.reshape(2,32)   # reshape used to change dimension of array, while doing it ,we cant change size of an array.

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [34]:
arr4.reshape(4,16)  # reshape(rows,column)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [35]:
arr4.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [36]:
arr4.reshape(16,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [40]:
arr4.reshape(32,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50],
       [51, 52],
       [53, 54],
       [55, 56],
       [57, 58],
       [59, 60],
       [61, 62],
       [63, 64]])

In [38]:
arr4.reshape(64,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])

In [39]:
arr4.reshape(-1,1)   # to interchange rows and column

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])